---
output:
  html_document: 
    css: style.css
    highlight: default
    theme: paper
---

<br>

##### **Day 1: (6/3) Probability**

1. Participant and Course Introduction
2. [What Sets Bayes Apart?](content/lectures/WhatSetsBayesApart.pdf)
3. Differences among the three branches of statistics illustrated with confidence envelopes
4. [Rules of Probability](content/lectures/RulesProbability.pdf) & [Probability Lab 1](content/labs/ProbabilityLab1.html)
5. [Probability Concepts and Notation](content/lectures/ProbabilityConceptsDistributions.pdf)
6. [Probability Distributions](content/lectures/ProbabilityConceptsDistributions.pdf) & [Probability Lab 2](content/labs/ProbabilityLab2.html)
7. [Probability Distributions Boardwork](content/boardwork/ProbabilityDistributions.pdf)
8. [Distributional Cheatsheet](content/handouts/DistributionCheatSheet.pdf)
9. Welcome Happy Hour at SESYNC!

Review Hobbs and Hooten chapters 1-3.

<br>

##### **Day 2: (6/4) Likelihood & Bayes' Theorem**

1. [Marginal Distributions](content/lectures/MarginalDistributions.pdf) & [Probability Lab 3](content/labs/ProbabilityLab3.html)
2. [Moment Matching](content/lectures/ProbabilityConceptsDistributions.pdf) & [Probability Lab 4](content/labs/ProbabilityLab4.html)
3. [Likelihood](content/lectures/Likelihood.pdf) & [Lab](content/labs/LikelihoodLab.html)
4. [Likelihood Lab Excel File](content/handouts/HemlockLightLikelihood.xlsx) & [Answer](content/handouts/HemlockLightLikelihoodAnswers.xlsx)

Review Hobbs and Hooten chapters 3.5-4.

<br>

##### **Day 3: (6/5) Intro to Bayesian Statistics & Markov Chain Monte Carlo**

1. [Likelihood Lab Continued](content/labs/LikelihoodLab.html)
2. [Bayes' Theorem](content/lectures/BayesTheorem.pdf) & [Lab](content/labs/BayesTheoremLab.html) 
3. [More about Priors I](content/lectures/MoreAboutPriors1.pdf) & [Lab](content/labs/ConjugatePriorsLab.html) 
4. [Beta-binomial Conjugacy Derivation](content/handouts/DerivationBetaBinomialConjugate.pdf)

Review Hobbs and Hooten chapters 5 and 7.

<br>

##### **Day 4: (6/6) JAGS and Model Inference**

1. [MCMC Gibbs Sampling](content/lectures/MCMC1.pdf) & [MCMC Lab 1](content/labs/MCMCLab1.html)
2. [MCMC Gibbs Sampling Math](content/handouts/MCMCMath1.pdf)
3. [JAGS Primer](content/lectures/JAGSPrimerMCMCVis.pdf) & [Lab Answers](content/labs/JAGSPrimerLab.html)
4. [MCMC Metropolis-Hastings](content/lectures/MCMC2.pdf) (optional) & [MCMC Lab 2](content/labs/MCMCLab2.html) (optional)

Review Hobbs and Hooten chapter 7-8.

<br>

##### **Day 5: (6/7) Bayesian Regression & Multi-Level Modeling**

1. [JAGS Primer Continued](content/lectures/JAGSPrimerMCMCVis.pdf) & [Lab Answers](content/labs/JAGSPrimerLab.html)
2. [JAGS Problems Lab](content/labs/JAGSProblemsLab.html) 
3. [Inference From a Single Model](content/lectures/InferenceFromSingleModel.pdf)
4. [Bayesian Regression](content/lectures/BayesianRegression.pdf)
5. [Lognormal Explanation](content/handouts/lognormalExplanation.pdf)

Review Hobbs and Hooten chapter 6.

<br>

##### **Day 6: (6/8) Off**

<br>

##### **Day 7: (6/9) Multi-Level Modeling**

1. [Multi-Level Modeling](content/lectures/MultiLevelRegression.pdf)
2. [Multi-Level Modeling Lab](content/labs/MultiLevelModelingLab.html)

Review Hobbs and Hooten chapters 6, 10-12.

<br>

##### **Day 8: (6/10) Multi-Level Modeling and Model Checking**

1. [Multi-Level Modeling Lab Continued](content/labs/MultiLevelModelingLab.html)
2. [Model Checking](content/lectures/ModelChecking.pdf) & [Lab](content/labs/MultiLevelModelingLab.html)
3. [Writing Hierarchical Models](content/lectures/WritingHierarchicalModels.pdf) & [Lab](content/labs/ModelBuildingLab.html)

Review Hobbs and Hooten chapters 6, 8, 10-12.

<br>

##### **Day 9: (6/11) Writing Hierarchical Models and Mixture Models**

1. [Writing Hierarchical Models Lab Continued](content/labs/ModelBuildingLab.html)
2. [More About Priors II](content/lectures/MoreAboutPriors2.pdf)
3. [Mixture Models, Zero Inflation & Occupancy](content/lectures/MixtureModels.pdf) & [Lab](content/labs/MixtureModelsLab.html)

<br>

##### **Day 10: (6/12) Occupancy Models, Ordinal Models & Model Selection**

1. [Swiss Birds Lab](content/labs/SwissBirdsLab.html)
2. [Ordinal Models](content/lectures/OrdinalModels.pdf) & [Lab](content/labs/OrdinalLab.html)
3. [Model Selection](content/lectures/ModelSelection.pdf) & [Lab](content/labs/ModelSelectionLab1.html)
4. [Model Selection Lab Math](content/handouts/ModelSelectionMath.pdf)

<br>

##### **Day 11: (6/13) Dynamic Models & Spatial Modeling**

1. [Course Evaluation Survey](https://docs.google.com/forms/d/e/1FAIpQLSf4uvntNIaDYeqmV5g-Wh-YjgdtVIA7yrCz3iQ1i1KfY4MMMQ/viewform)
2. [Dynamic Models](content/lectures/DynamicModels.pdf) & [Lynx Lab](content/labs/LynxLab.html)
3. [Spatial Modeling for Continuous Data](content/lectures/ContinuousSpatialModels.pdf) & [Spatial Lab](content/labs/SpatialLab1.html)
4. [Spatial Modeling for Areal Data](content/lectures/ArealSpatialModels.pdf) (optional)
5. Farewell Happy Hour at SESYNC!

<br>

##### **Topics We Did Not Get To Cover**

1. [Designed Experiments](content/lectures/DesignedExperimentsCCC.pdf)
2. [Missing Data and Ignorability](content/lectures/MissingData.pdf)
