---
output:
  html_document: 
    css: style.css
    highlight: default
    theme: paper
---

<br>

##### **Day 1: (12/7) Probability**
Mornging
1. Introduction to course and  
[What Sets Bayes Apart?](content/lectures/WhatSetsBayesApart.pdf) 
3. Differences among the three branches of statistics illustrated with confidence envelopes ---Think about how to compile answers in real time
Participant introductions
4. [Rules of Probability](content/lectures/RulesProbability.pdf) & [Probability Lab 1](content/labs/ProbabilityLab1.html)

##### **Day 2: (12/8) Probability Distributions
Questions and go over yesterday's lab
1. [Probability Concepts and Notation](content/lectures/ProbabilityConceptsDistributions.pdf) 
2. [Probability Distributions Boardwork](content/boardwork/ProbabilityDistributions.pdf)
[Probability Distributions](content/lectures/ProbabilityConceptsDistributions.pdf) & [Probability Lab 2](content/labs/ProbabilityLab2.html)
3. [Distribution Cheatsheet](content/handouts/DistributionCheatSheet.pdf)
Break
4. [Marginal Distributions](content/lectures/MarginalDistributions.pdf) & [Probability Lab 3](content/labs/ProbabilityLab3.html)

Review Hobbs and Hooten chapters 1-3.

<br>

##### **Day 3: (12/9) Momment Matching and Likelihood **

1. Questions and lab review
2. [Moment Matching](content/lectures/ProbabilityConceptsDistributions.pdf) & [Probability Lab 4](content/labs/ProbabilityLab4.html)
Break
2. [Likelihood](content/lectures/Likelihood.pdf) & [Lab](content/labs/LikelihoodLab.html)
3. [Likelihood Lab Excel File](content/handouts/HemlockLightLikelihood.xlsx) & [Answer](content/handouts/HemlockLightLikelihoodAnswers.xlsx)

Review Hobbs and Hooten chapters 3.5-4.

<br>

##### **Day 4: (12/10) Bayes Theorem 

1. Questions and lab review
2. [Bayes' Theorem](content/lectures/BayesTheorem.pdf) & [Lab](content/labs/BayesTheoremLab.html) 
3. [More about Priors I](content/lectures/MoreAboutPriors1.pdf) & [Lab](content/labs/ConjugatePriorsLab.html) 
4. [Beta-binomial Conjugacy Derivation](content/handouts/DerivationBetaBinomialConjugate.pdf)

##### **Day 5: (12/11) Markov chain Monte Calro

1. Questions and lab review
2. [MCMC Gibbs Sampling](content/lectures/MCMC1.pdf) & [MCMC Lab 1](content/labs/MCMCLab1.html)
3. [MCMC Gibbs Sampling Math](content/handouts/MCMCMath1.pdf)
 Break 
4. [MCMC Lab 1](content/labs/MCMCLab1.html) continued
Review Hobbs and Hooten chapters 5 and 7.

<br>

##### **Day 6: (12/14) JAGS and Model Inference**

1. Questions and lab review
3. [JAGS Primer](content/lectures/JAGSPrimerMCMCVis.pdf) & [Lab Answers](content/labs/JAGSPrimerLab.html)
Break
3. [Inference From a Single Model](content/lectures/InferenceFromSingleModel.pdf)
4. [JAGS Problems
Lab](content/labs/JAGSProblemsLab.html) 

Review Hobbs and Hooten chapter 7-8.

<br>

##### **Day 7: (12/15) Bayesian Regression & Multi-Level Modeling**
1. Questions and lab review
2. [JAGS Problems
Lab](content/labs/JAGSProblemsLab.html) 
Break
3. [Bayesian Regression](content/lectures/BayesianRegression.pdf) several pseudo code examples, perhaps a problem (could be first of multi-level modeling problem set)


Review Hobbs and Hooten chapter 6.

<br>

##### **Day 8: (12/16) Multi-Level Modeling**
1. Questions and lab review
1. [Multi-Level Modeling](content/lectures/MultiLevelRegression.pdf)
2. [Multi-Level Modeling Lab](content/labs/MultiLevelModelingLab.html)
Break
3. [Multi-Level Modeling Lab](content/labs/MultiLevelModelingLab.html)
Review Hobbs and Hooten chapters 6, 10-12.

<br>

##### **Day 9: (12/17) Model Checking and writing hierarhcial models**
1. Questions and lab review
2. [Model Checking](content/lectures/ModelChecking.pdf) & [Lab](content/labs/MultiLevelModelingLab.html)
Break
3. [Writing Hierarchical Models](content/lectures/WritingHierarchicalModels.pdf) & [Lab](content/labs/ModelBuildingLab.html)

Review Hobbs and Hooten chapters 6, 8, 10-12.

<br>

##### **Day 10: (12/18) Concurrent sessions**  Concurrent sessions could include 3 of: 1) mixture models and occupancy 2) dynamic models 3) ordinal models 4) mark recapure models and data augmentation 5) model selection.  We could decide in advance or poll the class

Course evaluation & something on continuing your learning


4. [Mixture Models, Zero Inflation & Occupancy](content/lectures/MixtureModels.pdf) & [Lab](content/labs/MixtureModelsLab.html)

<br>

=====From before



##### **Day 10: (6/12) Occupancy Models, Ordinal Models & Model Selection**

1. [Swiss Birds Lab](content/labs/SwissBirdsLab.html)
2. [Ordinal Models](content/lectures/OrdinalModels.pdf) & [Lab](content/labs/OrdinalLab.html)
3. [Model Selection](content/lectures/ModelSelection.pdf) & [Lab](content/labs/ModelSelectionLab1.html)
4. [Model Selection Lab Math](content/handouts/ModelSelectionMath.pdf)

<br>

##### **Day 11: (6/13) Dynamic Models & Spatial Modeling**

1. [Course Evaluation Survey](https://docs.google.com/forms/d/e/1FAIpQLSf4uvntNIaDYeqmV5g-Wh-YjgdtVIA7yrCz3iQ1i1KfY4MMMQ/viewform)
2. [Dynamic Models](content/lectures/DynamicModels.pdf) & [Lynx Lab](content/labs/LynxLab.html)
3. [Spatial Modeling for Continuous Data](content/lectures/ContinuousSpatialModels.pdf) & [Spatial Lab](content/labs/SpatialLab1.html)
4. [Spatial Modeling for Areal Data](content/lectures/ArealSpatialModels.pdf) (optional)
5. Farewell Happy Hour at SESYNC!

<br>

##### **Topics We Did Not Get To Cover**

1. [Designed Experiments](content/lectures/DesignedExperimentsCCC.pdf)
2. [Missing Data and Ignorability](content/lectures/MissingData.pdf)
