---
output:
  html_document:
    css: ../_HeadersEtc/style.css
    highlight: default
    theme: paper
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Structure of the repo

The repository is set up to hold both the course materials and function as the course website. The website is bare bones on purpose since it will be updated many times during the course, and I felt simpler translates to less errors. The folder structure is as follows:

1. _Graphics: This folder contains all graphics used in any of the lectures and labs. I have made just a single folder for this purpose since there was a lot of redundancy between the old lab graphics and lecture graphics folders.

2. _HeadersEtc: This folder contains the css stylesheet used for the labs as well as the html script to make the lab answer button work. The files inside the folder `SESYNCBayes` provide the logo, authors, course title, and lecture beamer template. I centralized these files to make it easier to change these values for future course iterations.

3. _Lectures: This folder contains all the lecture .rmd, .lyx, or .tex files, each in its own subfolder.

4. _Labs: This folder contains all the lab .rmd files, each in its own subfolder.

5. content: This folder contains all the pdf or html lab and lecture files.

6. docs: This folder contains the live website and should not be altered, except by rebuilding the website (see below).

## YAML for labs


## Buttons for labs


## YAML for lectures




