---
title: "Conventons for Statistical Notation"
author: "Tom Hobbs"
date: "6/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are conventions for writing statistical models that exist for a reason: they make it easier to read equations and understand them.  Failing to adhere to these conventions will raise eyebrows with reviewers of your papers.  (Never give a reviewer a reason to knit his or her brow.) The following points outline the most important rules for writing mathematical expressions of statistical ideas.

* Brackets, i.e. $[\,]$ are used to indicate stochastic relationships and for no other purpose. As you will learn, $[a|b,c]$ means the probability or probability density of $a$ conditional on $b$ and $c$.  Do not use brackets in the same way you would use parentheses. For example, $\alpha((b-c)+(d+f))$  is correct; $\alpha[(b-c)+(d+f)]$ is incorrect. Do not use brackets for named distributions:  $\text{normal}(y\mid\mu,\sigma^2)$ and $ y \sim \text{normal}(\mu, \sigma^2)$ are correct; $\text{normal}[y\mid\mu,\sigma^2]$ and $ y sim \text{normal}[\mu, \sigma^2]$ are incorrect.
* Notate scalars as lowercase, math font, for example: $y,x,\sigma, \omega$
* Notate vectors as lowercase, math bold font, for example: $\mathbf{y,x,}\,\boldsymbol{\sigma, \omega}$
* Notate matrices as uppercase, math bold font,  $\mathbf{Y,X,}\,\boldsymbol{\Sigma,\Omega}$
* Notate distribution names using plain text font, for example: $\text{normal}(\mu, \sigma^2)$
* When possible, use single letters for response and predictor variables in models.  First choice for scalar responses is always $y$; for predictor variables is $x$; and for latent quantities, $z$. Vector and matrix forms use the same letters with appropriate bolding and capitalization. Other letters can be used as needed.
* Use Greek letters for model parameters, following the case and bolding conventions described above for scalars, vectors, and matrices.  
* Avoid using variable names like $precip$ or $temp$.  These make for cluttered equations and can be confused with multiplication. You can use subscripts to give greater meaning to single variables, for example, $\sigma_p$ or $x_{precip}$.  If you want to be strict, you should get in the habit of using a plain text font for these descriptive subscripts, for example $\sigma_{\text{p}}$ to conform to style for ESA journals. 
* The only time you should use multiplication symbols is at the left end of multi-line equations, as illustrated above in the equation array. Never use \* in mathematical expressions; \* is a coding symbol, not a mathematical one.  Write $\beta x_i$ not $\beta\times x_i$
* Use expanding brackets when needed.  For example: $\left(\frac{\mu^2}{\sigma^2} \right)$ not $(\frac{\mu^2}{\sigma^2})$.
